title: "Footer"
description: |
  Similar to header, this only footer is to used throughout the site. There is no need to apply any max length class onto it because the footer content already has the class applied, and the blue background colour is supposed to go from edge to edge. 
