title: "Buttons"
description: |
  Just some regular degular buttons :). Different button styles use different colour sets for their normal vs. hover states.

patterns:
  basic:
    title: "Basic"
    description: |
      The strongest, most attention-grabbing one, used for the most important action on the page. Should have only one per page. Should only be used in front of white backgrorund.
    width: 10em;

  ghost:
    title: "Ghost"
    description: |
      Mainly used for more subtle or secondary actions. Can be used in front of images, most likely on banners or next to basic buttons for contrast.
    width: 10em;

  light:
    title: "Light"
    description: |
      Used for actions that don't require utmost attention but are important nonetheless. Can have more than one per page.
    width: 10em;
