title: "Header"
description: |
  The main, consistent header is to used throughout the website. Header links provide direct navigation to different product category pages, make for a simpler shopping experience. There is some animation when hover over icon links (including the logo) and some Javascript applied to the navigation on smaller screen to make toggle navigation more lively.
