title: "Navigations"
description: |
  Different navigations used consistently throughout the site.

patterns:
  main-nav:
    title: "Main navigation"
    description: |
      Main navigation with all page links that will be included in the header. Toggle navigation on small and medium screens, fully visible on large screen.

  breadcrumb-nav:
    title: "Breadcrumb navigation"
    description: |
      Breadcrumb navigation used at top of product list.

  page-nav:
    title: "Page navigation"
    description: |
      Pagination used at the bottom of product listing page.

  filters:
    title: "Product filters"
    description: |
      Used on the left of product listing.
