title: "Links"
description: |
  Some of these links are media objects that behaves almost like a button, except they don't have hover states and are only included on specific objects, for example certain cards.
