title: "Links"
description: |
  I call them <em>Links</em> but they are actually a variety of elements, such as search field and icon buttons. These elements are insignificant and only appear on several specific patterns, for example on certain types of cards.

patterns:
  favourite:
    title: "Favourites"
    description: |
      Used on product thumbnail cards, to quickly add the product to <em>Favourites</em>.

  seller:
    title: "Seller"
    description: |
      Used specifically on product details card.

  artist:
    title: "Artist"
    description: |
      Used wherever the artist's name is needed. Acts same as <em>Seller</em> without thumbnail and rating.

  searchbar:
    title: "Search bar"
    description: |
      Used on header.

  close:
    title: "Close"
    description: |
      Used on pop-up elements to cancel/exit and go back.
