title: "Sections"
description: |
  Different sections on different pages. Most of these sections are created with a <code>heading</code> and a grid system, which has other patterns incorporated into, for example a grid of different cards.

patterns:
  featured-categories:
    title: "Featured products of the month"
    description: |
      Used on the homepage, this section promotes several product categories of the current month. This section is the first section on the homepage, coming right after the banner.

  featured-prints:
    title: "Find your favourite prints"
    description: |
      This section shows a variety of featured prints for used on the homepage.

  featured-artist:
    title: "Featured artists"
    description: |
      This section is for use on the homepage to promote artists and display several examples of their work.

  product-details:
    title: "Product details"
    description: |
      It's a product details card that appears when a user clicks on a product card in the product listing.
    background: --color-primary
    fields:
      - name: title
        type: string
        example: "La Muralla Roja"
      - name: description
        type: string
        example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consequat tellus et lorem pulvinar, a vulputate quam lacinia."
      - name: image
        type: string
        example: "pastel.jpg"
      - name: artist
        type: string
        example: "Jeanne d'Arts"
      - name: price-reg
        type: number
        example: 60.0
      - name: price
        type: number
        example: 36.0

  about:
    title: "About"
    description: |
      Consists of a heading stating inAn value proposition and a single paragraph about the company, this section is meant for use on the homepage.

  print-media:
    title: "Print media"
    description: |
      This section showcases several of inAn's print media that's available for artists and fans to create and purchase.

  newsletter:
    title: "Newsletter"
    description: |
      This section should be the last section of the homepage, located just above the footer. The pink background is important to create contrast.
    background: --color-accent-pink
