title: "Cards"
description: |
  Different cards used throughout the website. <i>(scroll down for preview)</i>.

patterns:
  product-card:
    title: "Product card"
    description: |
      Example of a product card which appears in product listing pages. The image, the seller info and the bottom button are clickable.
    width: 25%
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
      - name: button_text
        type: string
        example: "Add to Favourites"

  info-card:
    title: "Info card"
    description: |
      Info cards are used to draw customers' attention to short, concise information, for example sales or upcoming big changes. It consists of an image, descriptive text and a call-to-action button.
    fields:
      - name: title
        type: string
        example: "Big changes coming this June!"
      - name: text
        type: string
        example: "96 new cities for international shipping, 20+ new print medium, Summer Art Camps and many more exciting news coming this summer."
      - name: image
        type: string
        example: "pattern-funky-1.svg"

  img-card:
    title: "Image card"
    description: |
      Image card consists of a clickable image and text, and is used to showcase artworks on main page. Hovering over the image brings up a heart icon to quickly add the item to <i>Favourites</i>.
    fields:
      - name: title
        type: string
        example: "Abstract Jungle Pattern"
      - name: image
        type: string
        example: "img-card.jpg"
      - name: artist_name
        type: string
        example: "George W. Brush"
    width: 25%

  thumbnail-card-sq:
    title: "Thumbnail card"
    description: |
      A simple, square-formatted image card to show thumbnail of items. This card is used for not just products, therefore it doesn't have an <i>add to Favourites</i> feature.
    fields:
      - name: title
        type: string
        example: "Throw pillows"
      - name: image
        type: string
        example: "square-pillow.jpg"
    width: 25%

  bunch-o-cards:
    title: "Cards preview"
    description: |
      Just a bunch-o-cards (for preview).
