title: "Cards"
description: |
  Different cards used throughout the website.

patterns:
  bunch-o-cards:
    title: "Cards preview"
    description: |
      Just a bunch-o-cards (for preview).

  product-card:
    title: "Product card"
    description: |
      Example of a product card which appears in product listing pages. The image, the seller info and the bottom button are clickable.

  info-card:
    title: "Info card"
    description: |
      Info cards are used to draw customers' attention to short, concise information, for example sales or upcoming big changes. It consists of an image, descriptive text and a call-to-action button.

  img-card:
    title: "Image card"
    description: |
      Image card consists of a clickable image and text, and is used to showcase artworks on main page. Hovering over the image brings up a heart icon to quickly add the item to <i>Favourites</i>.
