title: "Form"
description: |
  Different form fields used on checkout page.

patterns:
  personal:
    title: "Personal information"
    description: |
      Appears at the very top of checkout form.
    background: --color-primary
    width: 50em;

  contact:
    title: "Contact information"
    description: |
      Contact info including email, phone number and address.
    background: --color-primary
    width: 50em;

  shipping:
    title: "Shipping"
    description: |
      Radio list for choosing shipping options.
    width: 75em;

  payment:
    title: "Payment"
    description: |
      lul.
    background: --color-primary
    width: 50em;

  text-area:
    title: "Text area"
    description: |
      Multi-line text input (idk what to use this for yet).
    background: --color-primary
    width: 50em;

  select:
    title: "Drop-down select"
    description: |
      Drop-down select.
    fields:
      - name: option-1
        type: string
        example: "one"
      - name: option-2
        type: string
        example: "two"
      - name: option-3
        type: string
        example: "three"
    background: --color-primary
    width: 50em;
