title: "Form"
description: |
  Different form fields used on check-out page.

patterns:
  name:
    title: "Name"
    description: |
      First and last name.
    background: --color-primary
    width: 45em;

  contact:
    title: "Contact information"
    description: |
      Contact info input including email, phone number and address.
    background: --color-primary
    width: 45em;

  select:
    title: "Drop-down select"
    description: |
      Drop-down select.
    background: --color-primary
    width: 45em;

  shipping:
    title: "Shipping"
    description: |
      Radio list for choosing shipping options.
    width: 70em;

  text-area:
    title: "Text area"
    description: |
      Multi-line text input (idk what to use this for yet).
    background: --color-primary
    width: 45em;
