title: "Banners"
description: |
  These are the banners that appear at the top of the pages. They are either animated with transitions or static. Although animated banners are fun and all, static ones are favoured for accessibility reasons.
